include("Class_point.jl")
include("Class_iterate.jl")
include("misc.jl")
include("eval.jl")
include("Class_QP.jl")
include("Class_cutest.jl")
#include("Class_proximal.jl")
include("Class_homog.jl")
#include("Class_infeas.jl")
include("summary.jl")
include("process_results.jl")
include("plots.jl")

function IpoptSolve(nlp)
    tic()
    solver = IpoptSolver(print_level=5, max_iter=3000, bound_relax_factor=0.0, nlp_scaling_method="none")
    #,mehrotra_algorithm="yes") #, tol_dual_abs=1e-6)
    #solver = IpoptSolver(print_level=5, tol=1e-8)
    mp = NLPModels.NLPtoMPB(nlp, solver)
    MathProgBase.optimize!(mp)
    @show norm(mp.inner.mult_g, Inf)
    #y = MathProgBase.getdual(mp)
    solver = MathProgBase.getrawsolver(mp)
    #finalize(nlp_raw2)
    toc();
end
